### ISSUE TITLE
Remote V-REP API

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#45]
We need to be able to communicate with the V-REP simulator from the Twin (an initial idea). I looked at the RPC support in V-REP and here is what I have found:

http://www.coppeliarobotics.com/helpFiles/en/remoteApiModusOperandi.htm

This made me think that the remote API is still quite low-level. We need some ontology for the robots and I would like to create a REST server that would operate that ontology and communicate over a socket with the V-REP (if we manage to get it under Docker, we might co-locate them on a same kube pod).

Docs:

http://www.coppeliarobotics.com/helpFiles/en/remoteApiServerSide.htm
http://www.coppeliarobotics.com/helpFiles/en/remoteApiClientSide.htm

Otherwise V-REP has C++ APIs: http://www.coppeliarobotics.com/helpFiles/en/mainClientApplication.htm

**Comment by KRaizer** [comment]
Hello ,
There a number of ways to communicate with VREP from outside. Of the top of my head:
- Remote API: The easiest, and the one we used for the scene using Kuka's youBot you can see in the repository at the moment (why do you say it is too low level?).
- ROS Interface: More work to setup, but once you do it you can access tons of libraries and features from ROS (robot operating system: [http://www.ros.org/](http://www.ros.org/)).
- Custom Socket communication: All by hand. Lots of work here and not much gain compared to remotAPI as far as I know.

The team here in Indaiatuba are currently working on setting up the simulation to work with ROS instead of using remoteAPI, for the aforementioned reasons.

Regardless, I should have added an example python script to access the robots from outside simulation. I'll do that this week. 

A good link to take a look at is this one if you are eager to learn more about it: [http://www.coppeliarobotics.com/helpFiles/en/writingCode.htm](http://www.coppeliarobotics.com/helpFiles/en/writingCode.htm)

By the way, I was thinking about ways to add an ontology to the robot's working memory, once we manage to integrate SOAR with ROS to control our robots. Maybe we can discuss this on our next meeting?

**Comment by KRaizer** [comment]
I started working on that example python script to access the simulation but found out another issue in the calling of external lua scripts. I'll attend to that first and get back to this after it is solved.

**Comment by konstantino** [comment]
ElIoT (https://github.com/Alliasd/ELIoT/blob/master/eliot.todo) should be considered for this exercise given that it provides an easy way to simulate devices that talk IPSO and support LWM2M

**Comment by bluelancer** [comment]
ELIoT simulation is pushed as branch 'ELIoT'

**Comment by berezovskyi** [comment]
@bluelancer please open a Pull Request for that branch and remove (plus gitignore) the `node_modules` directories in it.

**Comment by berezovskyi** [comment]
I think this is to be handled by the ROS Nodes, out of scope for the Twins.
