### ISSUE TITLE
Trouble modelling certain classes

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#69]
I have a trouble representing extra properties on the class definitions, such as:

<img width="747" alt="screen shot 2018-02-17 at 01 51 35" src="https://user-images.githubusercontent.com/64734/36336123-562ec4c0-1385-11e8-852e-2afc956b1221.png">

and

<img width="479" alt="screen shot 2018-02-17 at 01 51 43" src="https://user-images.githubusercontent.com/64734/36336124-5c37157a-1385-11e8-8a55-07afea58e93b.png">

---

@jadelkhoury, what do you think will be the best way to proceed?

**Comment by berezovskyi** [comment]
Just tested against http://aide.md.kth.se:3020/planner and:

- we can get away without supplying `sh:order` (maybe it did blow up in my face _just yet_)
- we get a 500 error if we try to mess with `pddl:parameter` definition

**Comment by jadelkhoury** [comment]
A number of questions so I understand the problem first:

1. Are the figures you show vocabularies or shape domain specifications? 
2. The text below the figure: is that what is being produced or what you want to produce? 
3. I wonder about your usage of oslc:instanceShape in the rdfs:class definitions. What is the purpose of that? Seems confusing for me. You sure this is correct usage of instanceShape? 
4. What you mean “representing extra properties on the class definitions”? In Lyo Designer? Because there we don’t (yet) support the definition of properties for an rdfs:class

**Comment by berezovskyi** [comment]
@eanevul @likelion we chatted with Jad on the phone some time ago and decided to fake it for the upcoming paper prototype, but I wonder if you could address @jadelkhoury's question no. 3, please?

**Comment by likelion** [comment]
@berezovskyi @jadelkhoury I'm quite sure that the usage of `oslc:instanceShape` is correct. According to the [spec](https://tools.oasis-open.org/version-control/svn/oslc-core/trunk/specs/resource-shape.html#instanceShape), the `oslc:instanceShape` property is used to link any described resource with a shape resource that describes its contents. The purpose in this case is to check that the user-defined `:on` class has all the necessary properties defined according to the `pddl:PredicateShape` shape, mostly for the sake of debugging. The prolog OSLC library will verify shape compliance every time it creates or copies a resource in memory with associated shape(s).

**Comment by berezovskyi** [comment]
Closing for now, we worked around this. Will reopen if needed.
