### ISSUE TITLE
goal-ontology: design goal ontology for warehousecontroller

### ISSUE THREAD

**Issue by swarupmohalik** [EricssonResearch/scott-eu#9]
Warehousecontroller takes the mission from MOO_Manager and generates goal which is to be
served by the OSLC server attached to the warehousecontroller.  When Warehousecontroller calls the planner, it puts the URI for the goal and URI for the current state on the message queue meant for the planner adapter. Planner adapter pulls the goal and state RDFs and processes them for planner reasoner.

**Comment by berezovskyi** [comment]
Hi @swarupmohalik!

In regard to calling the Planning service: I think that it is still valid to do HTTP calls even when we have messaging infrastructure. So I would suggest that we create a resource `PlanningRequest` that is managed by the Planning service and WarehouseController service creates a `PlanningRequest` via a POST request. The Planning service would hopefully reply with a *201 Created* code and the Location header to the newly created planning request. WarehouseController can then listen on the MQTT topic for the completion event of that planning request. The benefit of the HTTP call is an immediate feedback when a request has been registered (or rejected).

In regard to the state: I firmly believe the there is no single state S in our system, because everything is part of the global distributed state. In my view, Planning service would subscribe to the state updates of certain resource types (e.g. Robot waypoint position) and decide whether the state change should trigger replanning. BUT for now we are not ready to perform reactive planning just yet, so I suggest to pass the State as a property of the PlanningRequest together with the Mission or the set of Goals (which is the task of this bug to figure out) as well as the planning/execution deadlines (execution deadline might be part of the goal).

For now I have ignored the MOO part and used [mission.json](https://github.com/EricssonResearch/scott-eu/blob/master/warehousecontroller/mission.json) as the guideline for my RDF vocabulary. Here is how my two domains look now (@eanevul will probably blow the whole thing out of the water tomorrow):

<img width="1324" alt="screen shot 2017-07-11 at 01 30 52" src="https://user-images.githubusercontent.com/64734/28044643-e4a040d6-65d8-11e7-8444-280960d12081.png">

<img width="1458" alt="screen shot 2017-07-11 at 01 32 21" src="https://user-images.githubusercontent.com/64734/28044645-e89d9396-65d8-11e7-825c-0af95c28ef63.png">

Here is how the OSLC adaptors are connected right now in my prototype:

<img width="1208" alt="screen shot 2017-07-11 at 01 34 53" src="https://user-images.githubusercontent.com/64734/28044725-5076391e-65d9-11e7-8d98-03bbd76962a0.png">

And finally, in regard to the "served by the OSLC server attached to the warehousecontroller": I don't think we should "attach" the OSLC server, but implement the warehouse controller as an OSLC server. I just happen to have all the tooling in place for Java, we can implement OSLC discovery/serialisation/capability features using Flask as well if needed. @likelion is making an OSLC library for Prolog right now.

**Comment by berezovskyi** [comment]
@swarupmohalik please your comments from today telco here

**Comment by swarupmohalik** [comment]
Addressed in https://github.com/EricssonResearch/scott-eu/pull/42
